### ISSUE TITLE
Customising the rights and permissions of datadog_monitor

### ISSUE THREAD

**Issue by zl4bv** [DataDog/chef-datadog#289]
We're trying to run Datadog on Windows as a user that is not part of the Administrators group and therefore the agent service fails to start because it cannot read from the config file:

```
Traceback (most recent call last):
  File "win32\agent.pyc", line 79, in __init__
  File "win32\agent.pyc", line 325, in __init__
  File "jmxfetch.pyc", line 115, in configure
  File "jmxfetch.pyc", line 198, in get_configuration
IOError: [Errno 13] Permission denied: u'C:\\ProgramData\\Datadog\\conf.d\\http_check.yaml'
```

I tried modifying the datadog_monitor resource to allow customisation of the permissions, and while this was successful for the Linux permissions, I did not have the same level of success with the Windows rights attribute. Since the rights attribute takes multiple arguments and can be specified multiple times it becomes a little more difficult to expose in a LWRP.

For now I'm using the template and service resources directly in my recipes, but I'm wondering if there is a better way of addressing this issue.

**Comment by miketheman** [comment]
@olivielpeau Could you explore this?
