### ISSUE TITLE
agent repeatedly failing to install on chef 12.7.2 with OpsWorks

### ISSUE THREAD

**Issue by eedwardsdisco** [DataDog/chef-datadog#321]
Cookbook Version 2.4.0
OpsWorks Agent Version 4016
Chef Version 12.7.2

Receiving `No candidate version available for datadog-agent`

This is causing chef run to fail, and does not resolve upon additional runs.

```
[2016-07-05T21:18:40+00:00] INFO: Processing apt_package[datadog-agent] action install (datadog::_install-linux line 42)
[0m
================================================================================[0m
[31mError executing action `install` on resource 'apt_package[datadog-agent]'[0m
================================================================================[0m

[0mChef::Exceptions::Package[0m
-------------------------[0m
No candidate version available for datadog-agent[0m

[0mCookbook Trace:[0m
---------------[0m
/var/chef/runs/921489e3-34a3-4d27-bc90-36edf4130f30/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'[0m

[0mResource Declaration:[0m
---------------------[0m
# In /var/chef/runs/921489e3-34a3-4d27-bc90-36edf4130f30/local-mode-cache/cache/cookbooks/datadog/recipes/_install-linux.rb
[0m
[0m 42:   package 'datadog-agent' do
[0m 43:     version dd_agent_version
[0m 44:     action node['datadog']['agent_package_action'] # default is :install
[0m 45:   end
[0m 46: end
[0m
[0mCompiled Resource:[0m
------------------[0m
# Declared in /var/chef/runs/921489e3-34a3-4d27-bc90-36edf4130f30/local-mode-cache/cache/cookbooks/datadog/recipes/_install-linux.rb:42:in `from_file'
[0m
[0mapt_package("datadog-agent") do
[0m  package_name "datadog-agent"
[0m  action [:install]
[0m  retries 0
[0m  retry_delay 2
[0m  default_guard_interpreter :default
[0m  declared_type :package
[0m  cookbook_name "datadog"
[0m  recipe_name "_install-linux"
[0mend
[0m
[0mPlatform:[0m
---------[0m
x86_64-linux[0m

[0m[2016-07-05T21:18:40+00:00] INFO: Running queued delayed notifications before re-raising exception
[2016-07-05T21:18:40+00:00] ERROR: Running exception handlers
[2016-07-05T21:18:42+00:00] ERROR: Exception handlers complete
[2016-07-05T21:18:42+00:00] FATAL: Stacktrace dumped to /var/chef/runs/921489e3-34a3-4d27-bc90-36edf4130f30/local-mode-cache/cache/chef-stacktrace.out
[2016-07-05T21:18:42+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2016-07-05T21:18:42+00:00] ERROR: apt_package[datadog-agent] (datadog::_install-linux line 42) had an error: Chef::Exceptions::Package: No candidate version available for datadog-agent
[2016-07-05T21:18:44+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by eedwardsdisco** [comment]
Note that if I completely destroy the node that has the issue and re-create it, I was able to get past the issue, thus it appears to be intermittent. Other nodes within the same cluster using this code successfully worked on first try.

**Comment by olivielpeau** [comment]
This could have been caused by a network failure during the `apt-get update` that's triggered when the repository is installed on the first run.

Such a failure would cause the package install to fail on the first run with the error you posted, and on subsequent runs `apt-get update` is not run (since the repository is already installed), so the error persists.

Unfortunately the `apt` cookbook ignores all errors during the `apt-get update` step so I'm not sure there's a good way to avoid this problem (see https://github.com/chef-cookbooks/apt/blob/v3.0.0/providers/repository.rb#L198).

@eedwardsdisco It's been a while since you've opened this issue, but do you happen to have any info that would confirm/contradict my theory? :)

**Comment by eedwardsdisco** [comment]
I would suspect that an intermittent network issue could indeed cause the issue.

**Comment by olivielpeau** [comment]
Ok, thanks for your feedback!

IMO this issue can't be fixed cleanly until the following open issue on the `apt` cookbook has been resolved: https://github.com/chef-cookbooks/apt/issues/164

**Comment by betesh** [comment]
I just had this problem today and the cause is that DataDog's GPG key had expired.  See https://help.datadoghq.com/hc/en-us/articles/360000886852-Agent-APT-Repo-Key-Rotation.  Running the following command fixed it: `sudo apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 A2923DFF56EDA6E76E55E492D3A80E30382E94DE && sudo apt-get update`

**Comment by nia2k7** [comment]
I just had this issue today and running apt-get update on the instance resolved it. Thanks!
