### ISSUE TITLE
Upgrade chef-handler dependency for chef 13 support

### ISSUE THREAD

**Issue by rmoriz** [DataDog/chef-datadog#406]
Currently limited in metadata.rb to ~> 1.1

However that chef-handler version will not be compatible with Chef 13 as it uses deprecated features.

Problem:

```================================================================================
       Recipe Compile Error in /tmp/kitchen/cache/cookbooks/chef_handler/resources/default.rb
       ================================================================================
       
       Chef::Exceptions::DeprecatedFeatureError
       ----------------------------------------
       "Property `supports` of resource `chef_handler` overwrites an existing method. Please use a different property name. This will raise an exception in Chef 13. (CHEF-11)/tmp/kitchen/cache/cookbooks/chef_handler/resources/default.rb:31:in `class_from_file'.\nPlease see https://docs.chef.io/deprecations_property_name_collision.html for further details and information on how to correct this problem. at /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/formatters/doc.rb:419:in `deprecation'"
       
       Cookbook Trace:
       ---------------
         /tmp/kitchen/cache/cookbooks/chef_handler/resources/default.rb:31:in `class_from_file'
       
       Relevant File Content:
       ----------------------
       /tmp/kitchen/cache/cookbooks/chef_handler/resources/default.rb:
       
        24:              :class_name,
        25:              :source,
        26:              :supports
        27:  
        28:  attribute :class_name, kind_of: String, name_attribute: true
        29:  attribute :source, default: nil, kind_of: String
        30:  attribute :arguments, default: []
        31>> attribute :supports, kind_of: Hash, default: { report: true, exception: true }
        32:  
        33:  # we have to set default for the supports attribute
        34:  # in initializer since it is a 'reserved' attribute name
        35:  def initialize(*args)
        36:    super
        37:    @action = :enable
        38:    @supports = { report: true, exception: true }
        39:  end
        40:  
       
```

I suggest to enable  "deprecations_as_errors" in test-kitchen, e.g.

```yaml
provisioner:
  name: chef_zero
  deprecations_as_errors: true

```

**Comment by olivielpeau** [comment]
Thanks @rmoriz for reporting this issue. For reference it's also been discussed here: https://github.com/DataDog/chef-datadog/pull/388#issuecomment-280337523

We should try loosening the version constraint on `chef_handler` to allow versions 2.x and check that the recipe still works well. Going to add this to the milestone for Chef 13 support and queue some work on that.

Didn't know about the `deprecations_as_errors` option, definitely looks like something we should add to our test-kitchen setup in the CI, thanks.

**Comment by degemer** [comment]
Done in this PR: https://github.com/DataDog/chef-datadog/pull/414, will be part of 2.9.0 (to be released this week).

Although it seems that chef_handler 1.x is still compatible with Chef 13, see this comment for more details: https://github.com/DataDog/chef-datadog/pull/396#issuecomment-288841453

Well, at least we checked that we're compatible with chef_handler 2.x!
