### ISSUE TITLE
package resource needs to allow downgrade

### ISSUE THREAD

**Issue by haidangwa** [DataDog/chef-datadog#443]
On a RHEL6 server, our datadog-agent was manually upgraded to the latest version by an indiscriminate `yum update` by an admin not following our chef procedures. This upgraded the datadog-agent to a version newer than what we have configured  in a chef environment. When this occurs, a chef run fails with the following error.

```
 * yum_package[datadog-agent] action install
    
    ================================================================================
    Error executing action `install` on resource 'yum_package[datadog-agent]'
    ================================================================================
    
    Chef::Exceptions::Package
    -------------------------
    Installed package datadog-agent-5.14.1-1 is newer than candidate package datadog-agent-5.13.0-1
    
    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
    
    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/datadog/recipes/_install-linux.rb
    
     64:     yum_package 'datadog-agent' do
     65:       version dd_agent_version
     66:       retries package_retries unless package_retries.nil?
     67:       retry_delay package_retry_delay unless package_retry_delay.nil?
     68:       action node['datadog']['agent_package_action'] # default is :install
     69:       allow_downgrade node['datadog']['agent_allow_downgrade']
     70:     end
     71:   end
    
    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/datadog/recipes/_install-linux.rb:64:in `from_file'
    
    yum_package("datadog-agent") do
      package_name "datadog-agent"
      action [:install]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :yum_package
      cookbook_name "datadog"
      recipe_name "_install-linux"
      version "5.13.0-1"
      flush_cache {:before=>false, :after=>false}
    end
    
    Platform:
    ---------
    x86_64-linux
    
```

https://github.com/DataDog/chef-datadog/blob/master/recipes/_install-linux.rb#L41-L43 should allow for downgrade.

**Comment by haidangwa** [comment]
Closing this bug, because https://github.com/DataDog/chef-datadog/blob/master/recipes/_install-linux.rb#L69 alreadh handles this.
