### ISSUE TITLE
Chef_handler 3.0.0 breaks dd-handler recipe

### ISSUE THREAD

**Issue by dgreene-r7** [DataDog/chef-datadog#444]
`chef_handler` [v3.0.0](https://github.com/chef-cookbooks/chef_handler/tree/v3.0.0) was released earlier today and breaks the `dd-handler` recipe. 

```
     ================================================================================
    Error executing action `enable` on resource 'chef_handler[Chef::Handler::Datadog]'
    ================================================================================

    NoMethodError
    -------------
    No resource or method named `unregister_handler' for `LWRP resource chef_handler from cookbook chef_handler action provider "Chef::Handler::Datadog"'

    Cookbook Trace:
    ---------------
    /var/chef/cookbooks-0/chef_handler/resources/default.rb:37:in `block (2 levels) in class_from_file'
    /var/chef/cookbooks-0/chef_handler/resources/default.rb:34:in `each'
    /var/chef/cookbooks-0/chef_handler/resources/default.rb:34:in `block in class_from_file'
    /var/chef/cookbooks-0/datadog/recipes/dd-handler.rb:92:in `from_file'
    /var/chef/cookbooks-0/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:347:in `load_recipe'
    /var/chef/cookbooks-0/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:303:in `block in include_recipe'
    /var/chef/cookbooks-0/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:302:in `each'
    /var/chef/cookbooks-0/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:302:in `include_recipe'
    OUR COOKBOOK
    /var/chef/cookbooks-0/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:347:in `load_recipe'
    /var/chef/cookbooks-0/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:303:in `block in include_recipe'
    /var/chef/cookbooks-0/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:302:in `each'
    /var/chef/cookbooks-0/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:302:in `include_recipe'
    OUR COOKBOOK
    /var/chef/cookbooks-0/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:347:in `load_recipe'
    /var/chef/cookbooks-0/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:303:in `block in include_recipe'
    /var/chef/cookbooks-0/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:302:in `each'
    /var/chef/cookbooks-0/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:302:in `include_recipe'
    OUR COOKBOOK
    /var/chef/cookbooks-0/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:347:in `load_recipe'
    /var/chef/cookbooks-0/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:303:in `block in include_recipe'
    /var/chef/cookbooks-0/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:302:in `each'
    /var/chef/cookbooks-0/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:302:in `include_recipe'
    OUR COOKBOOK
    /var/chef/cookbooks-0/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:347:in `load_recipe'

    Resource Declaration:
    ---------------------
    # In /var/chef/cookbooks-0/datadog/recipes/dd-handler.rb

     52: chef_handler 'Chef::Handler::Datadog' do # rubocop:disable Metrics/BlockLength
     53:   def extra_endpoints
     54:     extra_endpoints = []
     55:     node['datadog']['extra_endpoints'].each do |_, endpoint|
     56:       next unless endpoint['enabled']
     57:       endpoint = Mash.new(endpoint)
     58:       endpoint.delete('enabled')
     59:       extra_endpoints << endpoint
     60:     end
     61:     extra_endpoints
     62:   end
     63:

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cookbooks-0/datadog/recipes/dd-handler.rb:52:in `from_file'

    chef_handler("Chef::Handler::Datadog") do
      action [:nothing]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :chef_handler
      cookbook_name :datadog
      recipe_name "dd-handler"
      source "chef/handler/datadog"
      arguments #<Chef::DelayedEvaluator:0x000000075a2768@/var/chef/cookbooks-0/datadog/recipes/dd-handler.rb:84>
      type {:report=>true, :exception=>true}
      class_name "Chef::Handler::Datadog"
      only_if { #code block }
    end


  ================================================================================
  Recipe Compile Error in OUR COOKBOOK
  ================================================================================

  NoMethodError
  -------------
  chef_handler[Chef::Handler::Datadog] (datadog::dd-handler line 52) had an error: NoMethodError: No resource or method named `unregister_handler' for `LWRP resource chef_handler from cookbook chef_handler action provider "Chef::Handler::Datadog"'

  Cookbook Trace:
  ---------------
    /var/chef/cookbooks-0/chef_handler/resources/default.rb:37:in `block (2 levels) in class_from_file'
    /var/chef/cookbooks-0/chef_handler/resources/default.rb:34:in `each'
    /var/chef/cookbooks-0/chef_handler/resources/default.rb:34:in `block in class_from_file'
    /var/chef/cookbooks-0/datadog/recipes/dd-handler.rb:92:in `from_file'
    /var/chef/cookbooks-0/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:347:in `load_recipe'
    /var/chef/cookbooks-0/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:303:in `block in include_recipe'
    /var/chef/cookbooks-0/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:302:in `each'
    /var/chef/cookbooks-0/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:302:in `include_recipe'
    OUR COOKBOOK
    /var/chef/cookbooks-0/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:347:in `load_recipe'
    /var/chef/cookbooks-0/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:303:in `block in include_recipe'
    /var/chef/cookbooks-0/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:302:in `each'
    /var/chef/cookbooks-0/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:302:in `include_recipe'
    OUR COOKBOOK
    /var/chef/cookbooks-0/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:347:in `load_recipe'
    /var/chef/cookbooks-0/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:303:in `block in include_recipe'
    /var/chef/cookbooks-0/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:302:in `each'
    /var/chef/cookbooks-0/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:302:in `include_recipe'
    OUR COOKBOOK
    /var/chef/cookbooks-0/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:347:in `load_recipe'
    /var/chef/cookbooks-0/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:303:in `block in include_recipe'
    /var/chef/cookbooks-0/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:302:in `each'
    /var/chef/cookbooks-0/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:302:in `include_recipe'
    OUR COOKBOOK
    /var/chef/cookbooks-0/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:347:in `load_recipe'

  Relevant File Content:
  ----------------------
  /var/chef/cookbooks-0/chef_handler/resources/default.rb:

   30:  # This action needs to find an rb file that presumably contains the indicated class in it and the
   31:  # load that file. It then instantiates that class by name and registers it as a handler.
   32:  action :enable do
   33:    class_name = new_resource.class_name
   34:    new_resource.type.each do |type, enable|
   35:      next unless enable
   36:
   37>>     unregister_handler(type, class_name)
   38:    end
   39:
   40:    handler = nil
   41:
   42:    require new_resource.source unless new_resource.source.nil?
   43:
   44:    _, klass = get_class(class_name)
   45:    handler = klass.send(:new, *collect_args(new_resource.arguments))
   46:


  Running handlers:
  Running handlers complete
  Chef Client failed. 0 resources updated in 02 seconds
```

Anywhere I've noted `OUR COOKBOOK` in the stacktrace above was just an `include_recipe` call that eventually leads to calling the `datadog::dd-handler` recipe.

Our suggested fix is to pin the `chef_handler` cookbook to the `2.1` line to prevent the new version from being installed.

**Comment by rmoriz** [comment]
related https://github.com/chef-cookbooks/chef_handler/issues/61

**Comment by kannan4k** [comment]
@dgreene-r7 We've received the same error when we upgraded to the latest version of chef_handler today. May I know how do you fixed this?
