### ISSUE TITLE
dd-handler recipe SSL Error

### ISSUE THREAD

**Issue by jfryer-runoranj** [DataDog/chef-datadog#603]
On Windows 2016, with datadog cookbook v2.16.1, and Chef Client 13.8.5, When trying to run the datadog:dd-handler recipe I get `[2019-04-10T22:19:11+00:00] ERROR: Report handler Chef::Handler::Datadog raised #<OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed>`

I've verified the SSL configuration to my chef server is fine. This is the only recipe that throws this error

```
Recipe: datadog::dd-handler[0m
  * chef_gem[chef-handler-datadog] action install (up to date)
  * chef_handler[Chef::Handler::Datadog] action nothing (skipped due to action :nothing)
Recipe: <Dynamically Defined Resource>[0m
  * zypper_package[insserv-compat] action install (skipped due to only_if)
  * windows_user[chefautomate] action create (skipped due to not_if)
  * directory[c:\chef\bin] action create (up to date)
  * directory[c:\chef\etc] action create (up to date)
  * directory[c:\chef\log\automate-liveness-agent] action create (up to date)
  * file[c:\chef\bin\automate-liveness-agent] action create (up to date)
  * file[c:\chef\etc\config.json] action create (up to date)
  * file[c:\chef\bin\automate_liveness_agent_task.ps1] action create (up to date)
  * powershell_script[Setup scheduled task at 30 minutes] action run (skipped due to not_if)
[0m
Running handlers:[0m
[2019-04-10T22:19:11+00:00] ERROR: Report handler Chef::Handler::Datadog raised #<OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed>
[2019-04-10T22:19:11+00:00] ERROR: C:/opscode/chef/embedded/lib/ruby/2.4.0/net/protocol.rb:44:in `connect_nonblock'
[2019-04-10T22:19:11+00:00] ERROR: C:/opscode/chef/embedded/lib/ruby/2.4.0/net/protocol.rb:44:in `ssl_socket_connect'
[2019-04-10T22:19:11+00:00] ERROR: C:/opscode/chef/embedded/lib/ruby/2.4.0/net/http.rb:948:in `connect'
[2019-04-10T22:19:11+00:00] ERROR: C:/opscode/chef/embedded/lib/ruby/2.4.0/net/http.rb:887:in `do_start'
[2019-04-10T22:19:11+00:00] ERROR: C:/opscode/chef/embedded/lib/ruby/2.4.0/net/http.rb:876:in `start'
[2019-04-10T22:19:11+00:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/dogapi-1.35.0/lib/dogapi/common.rb:97:in `connect'
[2019-04-10T22:19:11+00:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/dogapi-1.35.0/lib/dogapi/common.rb:117:in `request'
[2019-04-10T22:19:11+00:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/dogapi-1.35.0/lib/dogapi/v1/metric.rb:24:in `upload'
[2019-04-10T22:19:11+00:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/dogapi-1.35.0/lib/dogapi/v1/metric.rb:29:in `submit_to_api'
[2019-04-10T22:19:11+00:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/dogapi-1.35.0/lib/dogapi/v1/metric.rb:48:in `submit'
[2019-04-10T22:19:11+00:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/dogapi-1.35.0/lib/dogapi/facade.rb:98:in `emit_points'
[2019-04-10T22:19:11+00:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/dogapi-1.35.0/lib/dogapi/facade.rb:71:in `emit_point'
[2019-04-10T22:19:11+00:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-handler-datadog-0.11.0/lib/chef/handler/datadog_chef_metrics.rb:38:in `emit_to_datadog'
[2019-04-10T22:19:11+00:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-handler-datadog-0.11.0/lib/chef/handler/datadog.rb:77:in `send_report_to_datadog'
[2019-04-10T22:19:11+00:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-handler-datadog-0.11.0/lib/chef/handler/datadog.rb:34:in `block in report'
[2019-04-10T22:19:11+00:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-handler-datadog-0.11.0/lib/chef/handler/datadog.rb:32:in `each'
[2019-04-10T22:19:11+00:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-handler-datadog-0.11.0/lib/chef/handler/datadog.rb:32:in `report'
[2019-04-10T22:19:11+00:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5-universal-mingw32/lib/chef/handler.rb:259:in `run_report_unsafe'
[2019-04-10T22:19:11+00:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5-universal-mingw32/lib/chef/handler.rb:247:in `run_report_safely'
[2019-04-10T22:19:11+00:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5-universal-mingw32/lib/chef/handler.rb:125:in `block in run_report_handlers'
[2019-04-10T22:19:11+00:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5-universal-mingw32/lib/chef/handler.rb:123:in `each'
[2019-04-10T22:19:11+00:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5-universal-mingw32/lib/chef/handler.rb:123:in `run_report_handlers'
[2019-04-10T22:19:11+00:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5-universal-mingw32/lib/chef/handler.rb:135:in `block in <class:Handler>'
[2019-04-10T22:19:11+00:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5-universal-mingw32/lib/chef/client.rb:443:in `block in run_completed_successfully'
[2019-04-10T22:19:11+00:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5-universal-mingw32/lib/chef/client.rb:442:in `each'
[2019-04-10T22:19:11+00:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5-universal-mingw32/lib/chef/client.rb:442:in `run_completed_successfully'
[2019-04-10T22:19:11+00:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5-universal-mingw32/lib/chef/client.rb:301:in `run'
[2019-04-10T22:19:11+00:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5-universal-mingw32/lib/chef/application.rb:274:in `run_with_graceful_exit_option'
[2019-04-10T22:19:11+00:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5-universal-mingw32/lib/chef/application.rb:250:in `block in run_chef_client'
[2019-04-10T22:19:11+00:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
[2019-04-10T22:19:11+00:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5-universal-mingw32/lib/chef/application.rb:233:in `run_chef_client'
[2019-04-10T22:19:11+00:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5-universal-mingw32/lib/chef/application/client.rb:469:in `sleep_then_run_chef_client'
[2019-04-10T22:19:11+00:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5-universal-mingw32/lib/chef/application/client.rb:458:in `block in interval_run_chef_client'
[2019-04-10T22:19:11+00:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5-universal-mingw32/lib/chef/application/client.rb:457:in `loop'
[2019-04-10T22:19:11+00:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5-universal-mingw32/lib/chef/application/client.rb:457:in `interval_run_chef_client'
[2019-04-10T22:19:11+00:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5-universal-mingw32/lib/chef/application/client.rb:441:in `run_application'
[2019-04-10T22:19:11+00:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5-universal-mingw32/lib/chef/application.rb:59:in `run'
[2019-04-10T22:19:11+00:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5-universal-mingw32/bin/chef-client:26:in `<top (required)>'
[2019-04-10T22:19:11+00:00] ERROR: C:/opscode/chef/bin/chef-client:59:in `load'
[2019-04-10T22:19:11+00:00] ERROR: C:/opscode/chef/bin/chef-client:59:in `<main>'
  - Chef::Handler::Datadog[0m
Running handlers complete
```

**Comment by haidars** [comment]
are you using any proxy to connect to the external network
