### ISSUE TITLE
Deprecation CHEF-25

### ISSUE THREAD

**Issue by axl89** [DataDog/chef-datadog#824]
When running the CI with `deprecations_as_errors:true`, the [CHEF-25 deprecation error](https://docs.chef.io/deprecations_map_collision/) is shown as seen [here](https://app.circleci.com/pipelines/github/DataDog/chef-datadog/463/workflows/1ff50bfd-ad9a-4fcd-a02a-755b4354a579/jobs/5314):

```
       Starting Chef Client, version 14.12.9
       Creating a new client identity for dd-agent-handler5-ubuntu-1404 using the validator key.
       resolving cookbooks for run list: ["datadog::dd-agent", "datadog::dd-handler"]
       Synchronizing Cookbooks:
         - datadog (4.11.1)
         - chef_handler (3.0.3)
         - apt (7.4.0)
         - yum (6.1.1)
       Installing Cookbook Gems:
       Compiling Cookbooks...
       [2021-10-15T00:09:33+00:00] ERROR: Deprecation CHEF-25 from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.12.9/lib/chef/log.rb:51:in `caller_location'
       
         Resource chef_handler from a cookbook is overriding the resource from the client. Please upgrade your cookbook or remove the cookbook from your run_list before the next major release of Chef.
       
       Please see https://docs.chef.io/deprecations_map_collision.html for further details and information on how to correct this problem.
       
       ================================================================================
       Recipe Compile Error in /tmp/kitchen/cache/cookbooks/chef_handler/resources/default.rb
       ================================================================================
       
       Chef::Exceptions::DeprecatedFeatureError
       ----------------------------------------
       Deprecation CHEF-25 from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.12.9/lib/chef/log.rb:51:in `caller_location'
       
         Resource chef_handler from a cookbook is overriding the resource from the client. Please upgrade your cookbook or remove the cookbook from your run_list before the next major release of Chef.
       
       Please see https://docs.chef.io/deprecations_map_collision.html for further details and information on how to correct this problem.
       
       System Info:
       ------------
       chef_version=14.12.9
       platform=ubuntu
       platform_version=14.04
       ruby=ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux]
       program_name=/opt/chef/bin/chef-solo
       executable=/opt/chef/bin/chef-solo
       
       
       Running handlers:
       [2021-10-15T00:09:33+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2021-10-15T00:09:33+00:00] ERROR: Exception handlers complete
       Chef Client failed. 0 resources updated in 02 seconds
       [2021-10-15T00:09:33+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2021-10-15T00:09:33+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2021-10-15T00:09:33+00:00] FATAL: Chef::Exceptions::DeprecatedFeatureError: Deprecation CHEF-25 from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.12.9/lib/chef/log.rb:51:in `caller_location'
       
         Resource chef_handler from a cookbook is overriding the resource from the client. Please upgrade your cookbook or remove the cookbook from your run_list before the next major release of Chef.
       
       Please see https://docs.chef.io/deprecations_map_collision.html for further details and information on how to correct this problem.
```

**Comment by axl89** [comment]
Related with https://github.com/DataDog/chef-datadog/pull/822 (https://github.com/DataDog/chef-datadog/pull/822/commits/af442c5f8b36b65697ae8e6c88f6bec10c8b34a7 and https://github.com/DataDog/chef-datadog/pull/822/commits/c696b3a0b325ca5b6f37503a2539359124efc37f).

**Comment by albertvaka** [comment]
We document that deprecation warning in the README, but we can't do much about it if we want to stay compatible with older Chef versions. Enabling `deprecations_as_errors` on the CI could be helpful, so it sounds like a good idea to silence the warning there and enable that option. I've opened a PR with the change: https://github.com/DataDog/chef-datadog/pull/826
